name: Dependencies upgrade

on: workflow_dispatch

jobs:
  flake-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - uses: astral-sh/setup-uv@v7

    # https://docs.astral.sh/uv/concepts/projects/#upgrading-locked-package-versions
    - run: uv lock --upgrade

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v8
      with:
        title: "[Automated] Dependencies upgrade"
        commit-message: "[Automated] Dependencies upgrade"
        branch: "auto/uv-sync-upgrade"
        add-paths: uv.lock
        delete-branch: true
        labels: |
            automated pr
        reviewers: |
            dermatologist
